### ISSUE TITLE
Updates to match ENG version?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals.ja-jp#1]
The ENG version of PL-900 was updated some time ago by the CO to a new revision that trims down exercises, and thus the ENG version that is now official has only 6 .md files.

Will this localized repo (and all the other PL-900 localized repos) ever get this update?

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
The locrepo and the source repo show same files. I don't see error.
